resolver: lts-17.4
packages:
- '.'
extra-deps:
- language-glsl-0.3.0
- timeout-0.1.1@sha256:56c1d3321d7139d1f7ebf04d46c95d3a3f1c8c9e0f15666ae3ccd6bae6204b6e,1427

# Required to build on windows
- regex-posix-clib-2.7
flags:
  regex-posix:
     _regex-posix-clib: true
